from __future__ import annotations

PRESET_SOFTWARE = [
    {
        "name": "MySQL",
        "slug": "mysql",
        "kind": "database",
        "version_source": "endoflife",
        "source_key": "mysql",
        "winget_id": "Oracle.MySQL",
        "brew_formula": "mysql",
        "brew_cask": "",
        "official_url": "https://dev.mysql.com/downloads/mysql/",
        "use_official_link": False,
        "aliases": "mysql,my sql,mysqld,mysql server,mysql社区",
        "platforms": "windows,macos,linux",
        "notes": "Windows 优先用官方 MSI / winget 精确 ID，不要传短版本号",
    },
    {
        "name": "Node.js",
        "slug": "nodejs",
        "kind": "runtime",
        "version_source": "nodejs",
        "source_key": "node",
        "winget_id": "OpenJS.NodeJS.LTS",
        "brew_formula": "node",
        "brew_cask": "",
        "official_url": "https://nodejs.org/",
        "use_official_link": False,
        "aliases": "node,nodejs,node.js,node js",
        "platforms": "windows,macos,linux",
        "notes": "指定版本时下载官方 MSI，避免 winget 版本对不上",
    },
    {
        "name": "Python",
        "slug": "python",
        "kind": "runtime",
        "version_source": "python",
        "source_key": "python",
        "winget_id": "Python.Python.3.12",
        "brew_formula": "python",
        "brew_cask": "",
        "official_url": "https://www.python.org/downloads/",
        "use_official_link": False,
        "aliases": "python,py,python3,cpython",
        "platforms": "windows,macos,linux",
        "notes": "用官方 python-x.y.z-amd64.exe，winget 的 ID 自带大版本",
    },
    {
        "name": "Java (JDK)",
        "slug": "jdk",
        "kind": "runtime",
        "version_source": "adoptium",
        "source_key": "jdk",
        "winget_id": "EclipseAdoptium.Temurin.21.JDK",
        "brew_formula": "openjdk",
        "brew_cask": "temurin",
        "official_url": "https://adoptium.net/",
        "use_official_link": False,
        "aliases": "java,jdk,jre,openjdk,temurin,hotspot",
        "platforms": "windows,macos,linux",
        "notes": "Temurin 的 winget ID 含大版本，禁止 --version 17.4 这种写法",
    },
    {
        "name": "Git",
        "slug": "git",
        "kind": "tool",
        "version_source": "github",
        "source_key": "git-for-windows/git",
        "winget_id": "Git.Git",
        "brew_formula": "git",
        "brew_cask": "",
        "official_url": "https://git-scm.com/downloads",
        "use_official_link": False,
        "aliases": "git,git scm,gitbash,git bash",
        "platforms": "windows,macos,linux",
        "notes": "",
    },
    {
        "name": "Maven",
        "slug": "maven",
        "kind": "tool",
        "version_source": "endoflife",
        "source_key": "maven",
        "winget_id": "Apache.Maven",
        "brew_formula": "maven",
        "brew_cask": "",
        "official_url": "https://maven.apache.org/download.cgi",
        "use_official_link": False,
        "aliases": "maven,mvn,apache maven",
        "platforms": "windows,macos,linux",
        "notes": "",
    },
    {
        "name": "Redis",
        "slug": "redis",
        "kind": "database",
        "version_source": "endoflife",
        "source_key": "redis",
        "winget_id": "Redis.Redis",
        "brew_formula": "redis",
        "brew_cask": "",
        "official_url": "https://redis.io/download/",
        "use_official_link": False,
        "aliases": "redis,redis-server",
        "platforms": "windows,macos,linux",
        "notes": "Windows 无官方原生服务时回退 Memurai 开发版",
    },
    {
        "name": "Docker",
        "slug": "docker",
        "kind": "tool",
        "version_source": "static",
        "source_key": "docker",
        "winget_id": "Docker.DockerDesktop",
        "brew_formula": "",
        "brew_cask": "docker",
        "official_url": "https://www.docker.com/products/docker-desktop/",
        "use_official_link": False,
        "aliases": "docker,docker desktop,docker-desktop",
        "platforms": "windows,macos,linux",
        "notes": "Windows 需要 WSL2",
    },
    {
        "name": "Nginx",
        "slug": "nginx",
        "kind": "server",
        "version_source": "endoflife",
        "source_key": "nginx",
        "winget_id": "nginxinc.nginx",
        "brew_formula": "nginx",
        "brew_cask": "",
        "official_url": "https://nginx.org/en/download.html",
        "use_official_link": False,
        "aliases": "nginx,engine x",
        "platforms": "windows,macos,linux",
        "notes": "",
    },
    {
        "name": "Go",
        "slug": "go",
        "kind": "runtime",
        "version_source": "go",
        "source_key": "go",
        "winget_id": "GoLang.Go",
        "brew_formula": "go",
        "brew_cask": "",
        "official_url": "https://go.dev/dl/",
        "use_official_link": False,
        "aliases": "go,golang,go lang",
        "platforms": "windows,macos,linux",
        "notes": "指定版本用 go.dev 官方 MSI",
    },
    {
        "name": "Rust",
        "slug": "rust",
        "kind": "runtime",
        "version_source": "static",
        "source_key": "rust",
        "winget_id": "Rustlang.Rustup",
        "brew_formula": "rustup",
        "brew_cask": "",
        "official_url": "https://rustup.rs/",
        "use_official_link": False,
        "aliases": "rust,rustc,cargo,rustup",
        "platforms": "windows,macos,linux",
        "notes": "始终走 rustup，不锁小版本号给 winget",
    },
    {
        "name": "MongoDB",
        "slug": "mongodb",
        "kind": "database",
        "version_source": "endoflife",
        "source_key": "mongodb",
        "winget_id": "MongoDB.Server",
        "brew_formula": "",
        "brew_cask": "mongodb-community",
        "official_url": "https://www.mongodb.com/try/download/community",
        "use_official_link": False,
        "aliases": "mongo,mongodb,mongo db",
        "platforms": "windows,macos,linux",
        "notes": "",
    },
    {
        "name": "PostgreSQL",
        "slug": "postgresql",
        "kind": "database",
        "version_source": "endoflife",
        "source_key": "postgresql",
        "winget_id": "PostgreSQL.PostgreSQL",
        "brew_formula": "postgresql@16",
        "brew_cask": "",
        "official_url": "https://www.postgresql.org/download/",
        "use_official_link": False,
        "aliases": "postgres,postgresql,pgsql,pg",
        "platforms": "windows,macos,linux",
        "notes": "",
    },
    {
        "name": "VS Code",
        "slug": "vscode",
        "kind": "ide",
        "version_source": "static",
        "source_key": "vscode",
        "winget_id": "Microsoft.VisualStudioCode",
        "brew_formula": "",
        "brew_cask": "visual-studio-code",
        "official_url": "https://code.visualstudio.com/download",
        "use_official_link": True,
        "aliases": "vscode,vs code,visual studio code,code",
        "platforms": "windows,macos,linux",
        "notes": "有官方下载页，给链接不给脚本",
    },
    {
        "name": "IntelliJ IDEA",
        "slug": "idea",
        "kind": "ide",
        "version_source": "static",
        "source_key": "idea",
        "winget_id": "JetBrains.IntelliJIDEA.Community",
        "brew_formula": "",
        "brew_cask": "intellij-idea-ce",
        "official_url": "https://www.jetbrains.com/idea/download/",
        "use_official_link": True,
        "aliases": "idea,intellij,intellij idea,jetbrains idea",
        "platforms": "windows,macos,linux",
        "notes": "有官方下载页，给链接不给脚本",
    },
    {
        "name": "Homebrew",
        "slug": "homebrew",
        "kind": "tool",
        "version_source": "static",
        "source_key": "homebrew",
        "winget_id": "",
        "brew_formula": "",
        "brew_cask": "",
        "official_url": "https://brew.sh/",
        "use_official_link": False,
        "aliases": "brew,homebrew",
        "platforms": "macos,linux",
        "notes": "Windows 不适用",
    },
    {
        "name": "nvm",
        "slug": "nvm",
        "kind": "tool",
        "version_source": "github",
        "source_key": "coreybutler/nvm-windows",
        "winget_id": "CoreyButler.NVMforWindows",
        "brew_formula": "",
        "brew_cask": "",
        "official_url": "https://github.com/nvm-sh/nvm",
        "use_official_link": False,
        "aliases": "nvm,nvm-windows,nvs",
        "platforms": "windows,macos,linux",
        "notes": "Windows 用 nvm-windows，macOS/Linux 用 nvm-sh",
    },
]


def alias_list(software: dict | object) -> list[str]:
    raw = software["aliases"] if isinstance(software, dict) else (software.aliases or "")
    items = [software["name"] if isinstance(software, dict) else software.name, software["slug"] if isinstance(software, dict) else software.slug]
    items.extend(a.strip() for a in raw.split(",") if a.strip())
    return [a.lower() for a in items]


SEARCH_HINTS = {
    "php": {
        "name": "PHP",
        "slug": "php",
        "kind": "runtime",
        "version_source": "endoflife",
        "source_key": "php",
        "winget_id": "PHP.PHP",
        "official_url": "https://windows.php.net/download/",
        "use_official_link": False,
        "platforms": "windows,macos,linux",
    },
    "langchain": {
        "name": "LangChain",
        "slug": "langchain",
        "kind": "library",
        "version_source": "pypi",
        "source_key": "langchain",
        "winget_id": "",
        "official_url": "https://pypi.org/project/langchain/",
        "use_official_link": False,
        "platforms": "windows,macos,linux",
    },
    "pnpm": {
        "name": "pnpm",
        "slug": "pnpm",
        "kind": "tool",
        "version_source": "npm",
        "source_key": "pnpm",
        "winget_id": "pnpm.pnpm",
        "official_url": "https://pnpm.io/installation",
        "use_official_link": False,
        "platforms": "windows,macos,linux",
    },
    "yarn": {
        "name": "Yarn",
        "slug": "yarn",
        "kind": "tool",
        "version_source": "npm",
        "source_key": "yarn",
        "winget_id": "Yarn.Yarn",
        "official_url": "https://yarnpkg.com/",
        "use_official_link": False,
        "platforms": "windows,macos,linux",
    },
    "composer": {
        "name": "Composer",
        "slug": "composer",
        "kind": "tool",
        "version_source": "github",
        "source_key": "composer/composer",
        "winget_id": "Composer.Composer",
        "official_url": "https://getcomposer.org/",
        "use_official_link": False,
        "platforms": "windows,macos,linux",
    },
}


def heuristic_parse(query: str) -> dict | None:
    import re

    cleaned = query.strip()
    cleaned = re.sub(
        r"^(我想装|帮我装|请帮我安装|给我装|安装|download|install)\s*",
        "",
        cleaned,
        flags=re.I,
    ).strip(" 。.!！")
    if not cleaned:
        return None
    key = re.sub(r"[\s_-]+", "", cleaned.lower())
    if key in SEARCH_HINTS:
        return dict(SEARCH_HINTS[key])
    slug = re.sub(r"[^a-z0-9]+", "-", cleaned.lower()).strip("-")
    if len(slug) < 2:
        return None
    source = "pypi" if re.search(r"lang|torch|numpy|pandas|django|flask", slug) else "npm"
    return {
        "name": cleaned,
        "slug": slug,
        "kind": "library",
        "version_source": source,
        "source_key": slug,
        "winget_id": "",
        "official_url": "",
        "use_official_link": False,
        "platforms": "windows,macos,linux",
    }
